import { describe, expect, it } from 'vitest';
import { calcularCotizacionTecnica } from '@/modulos/cotizador/servicios/calcular-cotizacion-tecnica';
const base={moneda:'MXN',cantidad:10,recargoPorcentaje:25,descuentoPorcentaje:10};
const laser={material:'Acero',espesorMm:3,perimetroM:60,velocidadMMin:1,perforaciones:60,preparacionHoras:0.5,costoMaterial:100,gas:'O2',tarifas:{maquinaHora:60,preparacionHora:20,consumoGasHora:2,gas:{O2:5,N2:10,aire:1},segundosPerforacion:{Acero:{hasta3Mm:1,hasta6Mm:2,mayor6Mm:3}}}};
describe('motor de costo técnico sin tarifas implícitas',()=>{
 it('láser convierte minutos/segundos a horas y separa material',()=>{const r=calcularCotizacionTecnica({...base,laser});expect(r.costoMaterial).toBe(100);expect(r.costoServicios).toBe(81);expect(r.costoTotal).toBe(181);expect(r.precioUnitario).toBe(20.3625);expect(r.precioTotal).toBe(203.625);});
 it.each([[3,81],[3.1,82],[6,82],[6.1,83]])('espesor %s aplica el tramo correspondiente',(espesorMm,esperado)=>{expect(calcularCotizacionTecnica({...base,laser:{...laser,espesorMm}}).costoServicios).toBe(esperado);});
 it('acumula router, fabricación y otros sin perder subcontratos',()=>{const r=calcularCotizacionTecnica({...base,router:{horas:2,preparacionHoras:1,fresas:2,fresa:'ballnose',costoMaterial:30,tarifas:{maquinaHora:100,preparacionHora:20,endmill:5,ballnose:10}},fabricacion:{horasManoObra:2,horasSoldadura:1,horasAcabado:1,costoMaterial:50,subcontrato:40,tarifas:{manoObraHora:10,soldaduraHora:30,consumiblesHora:5,acabadoHora:15}},otros:{flete:12,adicionales:8}});expect(r.costoMaterial).toBe(80);expect(r.costoServicios).toBe(310);expect(r.costoOtros).toBe(60);expect(r.costoTotal).toBe(450);expect(r.procesos.reduce((s,p)=>s+p.total,0)).toBe(450);});
 it('doblado ajusta productividad por longitud y segundo operario',()=>{const r=calcularCotizacionTecnica({...base,cantidad:80,doblado:{complejidad:'media',longitudMm:1000,preparacionHoras:1,dosOperarios:true,costoMaterial:0,tarifas:{maquinaHora:100,preparacionHora:20,segundoOperarioHora:50,longitudMaximaMm:2000,factorLongitudMaxima:0.8,piezasHora:{simple:200,media:100,compleja:50}}}});expect(r.costoTotal).toBe(170);});
 it('snapshot serializable conserva parámetros sin depender del reloj ni del objeto original',()=>{const entrada={...base,laser:structuredClone(laser)};const r=calcularCotizacionTecnica(entrada);entrada.laser.costoMaterial=999;expect(r.entrada.laser?.costoMaterial).toBe(100);expect(JSON.parse(JSON.stringify(r))).toEqual(r);expect(calcularCotizacionTecnica({...base,laser})).toEqual(r);});
 it.each([0,-1,NaN,Infinity])('rechaza cantidad inválida %s',cantidad=>{expect(()=>calcularCotizacionTecnica({...base,cantidad,laser})).toThrow();});
 it('rechaza división por cero y material sin tiempo configurado',()=>{expect(()=>calcularCotizacionTecnica({...base,laser:{...laser,velocidadMMin:0}})).toThrow();expect(()=>calcularCotizacionTecnica({...base,laser:{...laser,material:'Desconocido'}})).toThrow(/Falta el tiempo/);});
 it('exige proceso, moneda y tarifas explícitos',()=>{expect(()=>calcularCotizacionTecnica(base)).toThrow();expect(()=>calcularCotizacionTecnica({...base,moneda:'EUR',laser})).toThrow();expect(()=>calcularCotizacionTecnica({...base,laser:{...laser,tarifas:undefined}})).toThrow();});
});
